/// Chapter 20 — Speak every language. Pinned to Examples/Localized and the
/// Localization article, which is the reference for every claim on the page.
public enum Ch20 {
    static let catalogCode = #"""
{
  "about.body": "Every string is resolved during the render pass, so switching language never reloads the page and never refetches anything.",
  "about.title": "About",
  "add.item": "Add item",
  "cart.empty": "Your cart is empty.",
  "direction.note": "This paragraph follows the writing direction of the active locale.",
  "items.count": "{count, plural, one {# item} other {# items}}",
  "logo.alt": "SwiftWUI logo",
  "nav.about": "About",
  "nav.home": "Home",
  "reset": "Reset",
  "search.placeholder": "Search items",
  "welcome.title": "Hello, {name}!"
}
"""#

    static let russianPluralCode = #"""
  "items.count": "{count, plural, one {# элемент} few {# элемента} many {# элементов} other {# элемента}}",
  "logo.alt": "Логотип SwiftWUI",
"""#

    static let generatedCode = #"""
// Generated by `swiftwui l10n generate`. Do not edit.
// Source of truth: Locales/*.json

import SwiftWUI

extension LocaleID {
    public static let ar = LocaleID("ar")!
    public static let en = LocaleID("en")!
    public static let ru = LocaleID("ru")!
}
"""#

    static let bodyCode = #"""
struct Home: Tag {
    @State private var count = 0
    @State private var query = ""

    var body: some Tag {
        Main {
            H1 { Text(L10n.welcomeTitle(name: "SwiftWUI")) }
            Img(src: "/logo.svg", alt: L10n.logoAlt(), width: 64, height: 64)

            // One key, one call site: the plural category is picked by the
            // locale's own CLDR rule inside the generated code.
            P { Text(count == 0 ? L10n.cartEmpty() : L10n.itemsCount(count: count)) }
            Div {
                Button(L10n.addItem()) { count += 1 }
                Button(L10n.reset(), disabled: count == 0) { count = 0 }
            }

            Input(value: $query, placeholder: L10n.searchPlaceholder())
            DirectionDemo()

            // Internal, prefix-free path — `Link` adds the locale prefix to the
            // href itself. Passing "/ru/about" here would match no route.
            Link("/about") { Text(L10n.navAbout()) }
        }
        .pageMeta(title: L10n.welcomeTitle(name: "SwiftWUI"))
    }
}
"""#

    static let switcherCode = #"""
// A language switcher built entirely from the environment: `\.availableLocales`
// is the declared locale set, so this component never imports the generated
// `L10n` and keeps working when a catalog is added.
struct LocaleSwitcher: Tag {
    @Environment(\.availableLocales) private var locales
    @Environment(\.locale) private var current
    @Environment(\.setLocale) private var setLocale

    var body: some Tag {
        Nav(class: "switcher") {
            ForEach(locales, id: \.identifier) { locale in
                Button(locale.identifier, disabled: locale == current) { setLocale(locale) }
            }
        }
    }
}
"""#

    static let declarationCode = #"""
struct MyApp: App {
    static var localization: Localization? {
        Localization(catalog: L10n.self, default: .en, strategy: .pathPrefix())
    }
    var body: some Tag { Router { Route("/") { Home() } } }
}
"""#

    static let renderOneCode = #"""
let page = try await StaticSite.render(MyApp.self, path: "/about",
                                       config: config, locale: .ru)
try StaticSite.writeDocument(page.html, path: page.path, outDir: out, subdir: page.subdir)
"""#

    public static let chapter = Chapter(
        slug: "speak-every-language", track: .ship, kicker: "CHAPTER · SHIP",
        title: "Speak every language",
        tagline: "JSON catalogs, generated Swift, and one decision about URLs — a site in three languages.",
        minutes: 25, kind: .chapter,
        sections: [
            Section(anchor: "l10n-catalogs", kicker: "01 · CATALOGS",
                    title: "One JSON file per language",
                    intro: "Translations live in a Locales/ folder inside the target that owns them, one file per language. The set of files is the set of declared locales — there is no config file and no list to keep in sync.",
                    steps: [
                        Step("swiftwui init scaffolds the first catalog at Sources/Locales/en.json.",
                             detail: "l10n add seeds a new one from an existing catalog, so it cannot create the first. An existing project writes that file by hand."),
                        Step("The top level is a flat object of strings; keys match [A-Za-z0-9._-]+."),
                        Step("Three things can appear in a value: {name}, a plural, and # inside a plural branch.",
                             detail: "{name} becomes a String parameter, {count, plural, …} an Int, and # is that number as bare digits."),
                        Step("Nothing quotes a literal { or #.",
                             detail: "A translator who writes \"Press {Ctrl}\" gets a key with a Ctrl: String parameter, silently. Pass the brace in from Swift instead."),
                        Step("Every locale of a key must agree on its placeholders, or generation fails with signatureMismatch.",
                             detail: "Russian, Ukrainian and Polish never produce the other branch for an Int — keep it as a copy of whichever branch the language really uses, and edit that one.",
                             panel: .code(CodePanel(file: "ru.json", code: russianPluralCode,
                                                    origin: .fragment(path: "Examples/Localized/Sources/Localized/Locales/ru.json")))),
                    ],
                    panel: .code(CodePanel(file: "en.json", code: catalogCode,
                                           origin: .fragment(path: "Examples/Localized/Sources/Localized/Locales/en.json")))),
            Section(anchor: "l10n-codegen", kicker: "02 · CODEGEN",
                    title: "Catalogs become Swift",
                    intro: "Nothing is looked up by string at runtime. Generation turns the catalogs into one L10n enum — a function per key, parameters typed from the placeholders — so a renamed key is a compile error.",
                    steps: [
                        Step("swiftwui l10n generate writes Generated/L10n.swift next to Locales/.",
                             detail: "build, ssg and dev all run it first, and dev watches Locales/*.json, so editing a translation triggers the same reload path as editing code."),
                        Step("Commit the generated file.",
                             detail: "It is ordinary source, it makes a stale translation visible in a diff, and --check is the CI gate that fails when it is out of date."),
                        Step("Every key must exist in every catalog.",
                             detail: "A missing one fails generation with missingKey; --allow-missing downgrades it to a warning and lets the default-locale fallback in section 03 do its job."),
                        Step("Each key becomes a function returning LocalizedText, never String.",
                             detail: "The language is not known until the value reaches a render.",
                             panel: .code(CodePanel(file: "L10n.swift", code: generatedCode,
                                                    origin: .fragment(path: "Examples/Localized/Sources/Localized/Generated/L10n.swift")))),
                        Step("The target needs exclude: [\"Locales\"] and .defaultIsolation(MainActor.self).",
                             detail: "Catalogs are codegen input, not a resource; without the isolation setting the build fails inside generated code with errors that read as a codegen bug."),
                        Step("The entry file is Entry.swift, not main.swift.",
                             detail: "Top-level code cannot coexist with the @main type the templates use, and the generated file is a second source file."),
                    ],
                    panel: .terminal(title: "zsh — polyglot", lines: [
                        TermLine(.command, "swiftwui init Polyglot"),
                        TermLine(.note, "> created Polyglot/ (template: basic), Sources/Locales/en.json included"),
                        TermLine(.command, "cd Polyglot && swiftwui l10n add ru && swiftwui l10n add ar"),
                        TermLine(.note, "> wrote Sources/Locales/{ru,ar}.json — every value marked TODO"),
                        TermLine(.command, "swiftwui l10n generate"),
                        TermLine(.note, "> wrote Sources/Generated/L10n.swift"),
                        TermLine(.command, "swift build"),
                    ])),
            Section(anchor: "l10n-text", kicker: "03 · TEXT",
                    title: "L10n inside a body",
                    intro: "A LocalizedText is a value, not a string: it carries the key and resolves during the render pass, once the locale is known — which takes the one declaration in section 05.",
                    steps: [
                        Step("Text takes a LocalizedText directly.",
                             detail: "So do Button, Img(alt:), Input(placeholder:), Textarea(text:placeholder:), .attribute(_:_:) and .pageMeta(title:)."),
                        Step("Container tags do not — H1(L10n.x()) does not compile.",
                             detail: "Wrap the text: H1 { Text(L10n.x()) }."),
                        Step("Page.title is a plain String, snapshotted before the locale is known.",
                             detail: "A localized document title goes through .pageMeta(title:) instead."),
                        Step("A localized .attribute is applied after every plain one, whatever order they were written in.",
                             detail: "Flattening is last-wins, so the localized value survives. That is the opposite of the usual reading."),
                        Step("Anywhere else, resolved(for:) with \\.locale hands you a plain String."),
                        Step("Resolution stops at the first hit: exact tag, primary language, default locale, then the key itself.",
                             detail: "Step two is asymmetric — an app that declares only pt-BR leaves a visitor reporting bare pt on the default locale."),
                    ],
                    panel: .code(CodePanel(file: "LocalizedApp.swift", code: bodyCode,
                                           origin: .fragment(path: "Examples/Localized/Sources/Localized/LocalizedApp.swift")))),
            Section(anchor: "l10n-switch", kicker: "04 · SWITCH",
                    title: "A switcher made of environment",
                    intro: "Switching language is a runtime action, and the component that performs it never sees the catalog.",
                    steps: [
                        Step("Four keys carry it: \\.locale, \\.layoutDirection, \\.availableLocales and \\.setLocale."),
                        Step("\\.availableLocales is the declared set, so a switcher needs no import of L10n.",
                             detail: "Order follows the generated catalog — canonical-tag alphabetical — not the order you added the files."),
                        Step("setLocale validates against that set — an unknown tag is a no-op plus a DEBUG warning.",
                             detail: "It writes <html lang> and dir, persists to localStorage, rewrites the URL under .pathPrefix, then invalidates the tree."),
                        Step("RTL needs no work of its own: an RTL locale sets <html dir=\"rtl\"> and logical CSS mirrors the document."),
                        Step("A locale change re-renders everything.",
                             detail: "Text resolves the locale outside the Observation window, so a targeted invalidation would miss exactly the components showing translated text."),
                    ],
                    panel: .code(CodePanel(file: "LocalizedApp.swift", code: switcherCode,
                                           origin: .fragment(path: "Examples/Localized/Sources/Localized/LocalizedApp.swift")))),
            Section(anchor: "l10n-strategy", kicker: "05 · STRATEGY",
                    title: "Three ways to carry a locale",
                    intro: "The strategy decides URL shape and dist layout, so it is fixed before anything renders. It is a build-time choice, not a runtime one.",
                    steps: [
                        Step("One declaration turns the feature on: static var localization on the App, returning Localization(catalog: L10n.self, default:, strategy:).",
                             detail: "nil — the default — keeps every branch inert: \\.availableLocales is empty, setLocale is a no-op, and the output is byte-for-byte what a monolingual build produced."),
                        Step(".pathPrefix() is the default: /about/ for the default locale, /ru/about/ for the rest.",
                             detail: "One indexable URL per language, hreflang and x-default in the head, and any static host can serve it."),
                        Step(".negotiated gives every language the same URL and one output folder each.",
                             detail: "The edge picks the folder from the swiftwui_locale cookie, then Accept-Language. On GitHub Pages or bare S3 only the default locale is reachable."),
                        Step(".client writes a single tree in the default locale and switches in the browser.",
                             detail: "The right answer where SEO does not apply — a dashboard behind a login."),
                        Step("Under .pathPrefix a URL that names a locale always wins.",
                             detail: "localStorage and navigator.languages are consulted only when it names none, which costs a returning visitor one English frame at /about/. .pathPrefix(detection: .urlOnly) opts out."),
                        Step("navigate takes the locale-free path — prefixes are added on output, never consumed on input.",
                             detail: "navigate(\"/ru/about\") becomes /ru/ru/about and matches nothing. Link already handles this: its href carries the prefix, its click does not."),
                    ],
                    panel: .code(CodePanel(file: "MyApp.swift", code: declarationCode,
                                           origin: .fragment(path: "Sources/SwiftWUI/SwiftWUI.docc/Localization.md")))),
            Section(anchor: "l10n-ssg", kicker: "06 · SSG",
                    title: "One build, one tree per locale",
                    intro: "Prerendering a localized site enumerates routes exactly once and then renders the whole page set once per locale.",
                    steps: [
                        Step("Patterns and .paths { } providers are locale-free and run a single time.",
                             detail: ".pathPrefix and .negotiated then render the page set per locale; .client renders the default locale only."),
                        Step("Every locale renders from a fresh Runtime, so .staticTask loaders run once per locale.",
                             detail: "Three languages means three times the build-time fetches. Cache an expensive loader outside the render — the framework cannot deduplicate, because a loader may fetch localized content."),
                        Step("Per document, <html lang> and dir follow the locale and canonical uses that locale's external path.",
                             detail: "Under .pathPrefix the head also carries hreflang plus x-default, and both need StaticSiteConfig.siteURL — a relative hreflang is ignored, so without an origin none is emitted."),
                        Step("Policies are per pattern, not per locale: .prerender(.never) suppresses every language of a route.",
                             detail: "Sitemap entries are keyed on the visible URL — one per locale under .pathPrefix, one in total under .negotiated."),
                        Step("StaticSite.render takes the locale explicitly and returns a page that knows where it goes.",
                             detail: "page.path is the browser-visible URL — locale prefix included — and page.subdir is the output folder .negotiated writes into. Both are decided by the render, so a .staticTask that called setLocale moves them too.",
                             panel: .code(CodePanel(file: "Entry.swift", code: renderOneCode,
                                                    origin: .fragment(path: "Sources/SwiftWUI/SwiftWUI.docc/Localization.md")))),
                    ],
                    panel: .terminal(title: "zsh — polyglot", lines: [
                        TermLine(.command, "swiftwui ssg --out dist"),
                        TermLine(.note, "> regenerated Sources/Generated/L10n.swift"),
                        TermLine(.note, "> generated 6 pages"),
                        TermLine(.note, "> two pages × three locales: dist/, dist/ru/, dist/ar/ — one tree per locale"),
                    ])),
        ],
        quiz: Quiz(questions: [
            Question(prompt: "Inside a component, navigate(\"/ru/about\") runs while the Russian locale is active. What does the visitor see?",
                     options: ["Nothing — the path becomes /ru/ru/about and matches no route",
                               "The Russian About page, since the prefix is already correct",
                               "The English About page, because the prefix is stripped",
                               "A build error: navigate rejects prefixed paths"],
                     correctIndex: 0,
                     explanation: "Prefixes are added on output, never consumed on input, so the active prefix lands on top of the one you typed. DEBUG builds print a warning; release builds show a blank page. Pass the locale-free \"/about\" and let Link and the runtime add the prefix."),
            Question(prompt: "An app declares pt-BR and nothing else. A visitor's browser reports plain pt. Which catalog answers?",
                     options: ["The default locale — a bare pt does not find pt-BR",
                               "pt-BR, because the primary language matches",
                               "Neither — every key renders as its own name",
                               "pt-BR, but only after a reload"],
                     correctIndex: 0,
                     explanation: "The fallback step matches supported.first { $0.identifier == requested.language }, which works from supported to requested: pt-BR is not the language pt. Declaring a region-less catalog is the fix."),
            Question(prompt: "A three-locale site prerenders a route whose body carries .staticTask { await load() }. How many times does load() run?",
                     options: ["Three — every locale renders from a fresh Runtime",
                               "Once — route enumeration is locale-free",
                               "Once per page, so twice for a two-page site",
                               "Three, unless the strategy is .pathPrefix"],
                     correctIndex: 0,
                     explanation: "Routes are enumerated once, but the page set renders once per locale and each locale gets a fresh Runtime, so build-time loaders repeat. Cache anything expensive or rate-limited outside the render; the framework cannot deduplicate, since a loader may legitimately fetch localized content."),
        ]))
}
