import Testing
import Foundation
import SwiftWUI
@testable import SwiftWUIToolchain

@Suite struct L10nEmitterTests {
    private func emit(_ catalogs: [String: String]) throws -> String {
        var parsed: [String: [String: L10nTemplate]] = [:]
        for (locale, json) in catalogs { parsed[locale] = try L10nCatalog.parse(json: json, locale: locale) }
        return try L10nEmitter.file(catalogs: parsed)
    }

    /// Pins the whole file: shape, locale and key ordering, canonicalisation,
    /// mangled local functions and the CLDR rule text. The suite's only defence
    /// against "the generated Swift changed" and "it no longer compiles".
    @Test func goldenFile() throws {
        let out = try emit([
            "en": #"{"greeting":"Hi, {name}!","cart":"{count, plural, one {# item} other {# items}}"}"#,
            "ru": #"{"greeting":"Привет, {name}!","cart":"{count, plural, one {# товар} few {# товара} many {# товаров} other {# товара}}"}"#,
            "pt-br": #"{"greeting":"Oi, {name}!"}"#,
        ])
        #expect(out == """
        // Generated by `swiftwui l10n generate`. Do not edit.
        // Source of truth: Locales/*.json

        import SwiftWUI

        extension LocaleID {
            public static let en = LocaleID("en")!
            public static let ptBR = LocaleID("pt-BR")!
            public static let ru = LocaleID("ru")!
        }

        public enum L10n {
            public static func cart(count: Int) -> LocalizedText {
                LocalizedText(key: "cart") { locale in
                    func _l_en() -> String {
                        switch _SWUIPlural.en(count) {
                        case .one: return String(count) + " item"
                        default: return String(count) + " items"
                        }
                    }
                    func _l_ru() -> String {
                        switch _SWUIPlural.ru(count) {
                        case .one: return String(count) + " товар"
                        case .few: return String(count) + " товара"
                        case .many: return String(count) + " товаров"
                        default: return String(count) + " товара"
                        }
                    }
                    switch locale.identifier {
                    case "en": return _l_en()
                    case "ru": return _l_ru()
                    default: break
                    }
                    switch locale.language {
                    case "en": return _l_en()
                    case "ru": return _l_ru()
                    default: return nil
                    }
                }
            }
            public static func greeting(name: String) -> LocalizedText {
                LocalizedText(key: "greeting") { locale in
                    func _l_en() -> String {
                        return "Hi, " + name + "!"
                    }
                    func _l_ptBR() -> String {
                        return "Oi, " + name + "!"
                    }
                    func _l_ru() -> String {
                        return "Привет, " + name + "!"
                    }
                    switch locale.identifier {
                    case "en": return _l_en()
                    case "pt-BR": return _l_ptBR()
                    case "ru": return _l_ru()
                    default: break
                    }
                    switch locale.language {
                    case "en": return _l_en()
                    case "ru": return _l_ru()
                    default: return nil
                    }
                }
            }
        }

        extension L10n: LocalizationCatalog {
            public static let supportedLocales: [LocaleID] = [.en, .ptBR, .ru]
        }

        enum _SWUIPlural {
            nonisolated static func en(_ value: Int) -> _PluralCategory {
                return value == 1 ? .one : .other
            }
            nonisolated static func ru(_ value: Int) -> _PluralCategory {
                let n = value.magnitude
                let mod10 = n % 10, mod100 = n % 100
                if mod10 == 1 && mod100 != 11 { return .one }
                if (2...4).contains(mod10) && !(12...14).contains(mod100) { return .few }
                return .many
            }
        }

        """)
    }

    @Test func emitsLocaleConstantsAndCatalogConformance() throws {
        let out = try emit(["en": #"{"a":"A"}"#, "ru": #"{"a":"А"}"#])
        // The file compiles inside the app's target, so it imports the framework itself.
        #expect(out.contains("\nimport SwiftWUI\n"))
        #expect(out.contains(#"public static let en = LocaleID("en")!"#))
        #expect(out.contains(#"public static let ru = LocaleID("ru")!"#))
        #expect(out.contains("extension L10n: LocalizationCatalog"))
        #expect(out.contains("supportedLocales: [LocaleID] = [.en, .ru]"))
    }

    @Test func emitsPlaceholderParameters() throws {
        let out = try emit(["en": #"{"welcome.title":"Hi, {name}!"}"#])
        #expect(out.contains("public static func welcomeTitle(name: String) -> LocalizedText"))
        #expect(out.contains(#"return "Hi, " + name + "!""#))
    }

    @Test func emitsPluralSwitch() throws {
        let out = try emit(["ru": #"{"n":"{count, plural, one {# товар} few {# товара} many {# товаров} other {# товара}}"}"#])
        #expect(out.contains("public static func n(count: Int) -> LocalizedText"))
        #expect(out.contains("switch _SWUIPlural.ru(count)"))
        #expect(out.contains("case .few:"))
        #expect(out.contains("static func ru(_ value: Int) -> _PluralCategory"))
    }

    @Test func escapesHostileValues() throws {
        // The catalog value is `x";import Foundation//` — a closing quote plus a
        // statement. Emitted raw it would end the literal and inject code.
        let out = try emit(["en": #"{"k":"x\";import Foundation//"}"#])
        #expect(out.contains(#""x";import Foundation//"#) == false)
        #expect(out.contains(#"return "x\";import Foundation//""#))
        #expect(!out.contains("\nimport Foundation//"))
    }

    @Test func escapesEveryControlCharacter() {
        let hostile = "a\\b\"c\nd\re\tf\u{0}g\u{2028}h\u{2029}i\u{1B}j\u{7F}k\u{85}l"
        let literal = SwiftLiteralEscaping.literal(hostile)
        #expect(literal == #""a\\b\"c\nd\re\tf\0g\u{2028}h\u{2029}i\u{001B}j\u{007F}k\u{0085}l""#)
        // Nothing that could terminate the line or hide from review survives.
        #expect(!literal.contains("\n"))
        #expect(!literal.contains("\r"))
        #expect(literal.unicodeScalars.allSatisfy { $0.value >= 0x20 && !(0x7F...0x9F).contains($0.value) })
    }

    /// Locale tags come from filenames and land in five identifier positions,
    /// where escaping cannot help — they have to be rejected instead.
    @Test func rejectsUnusableLocaleTags() {
        for tag in ["x = 1; import Foundation //", "en\"", "e", "", "foo-bar", "en-US-extra", "1n"] {
            #expect(throws: L10nError.self, "tag \(tag)") { _ = try emit([tag: #"{"a":"A"}"#]) }
        }
    }

    @Test func canonicalisesLocaleTags() throws {
        let out = try emit(["pt-br": #"{"a":"A"}"#, "EN": #"{"a":"A"}"#, "zh_hans_cn": #"{"a":"A"}"#])
        #expect(out.contains(#"public static let ptBR = LocaleID("pt-BR")!"#))
        #expect(out.contains(#"case "pt-BR": return _l_ptBR()"#))
        #expect(out.contains(#"public static let zhHansCN = LocaleID("zh-Hans-CN")!"#))
        #expect(out.contains("supportedLocales: [LocaleID] = [.en, .ptBR, .zhHansCN]"))
        // The raw filename never reaches the output.
        #expect(!out.contains("pt-br"))
        #expect(!out.contains("zh_hans_cn"))
    }

    @Test func rejectsTwoFilesForOneLocale() {
        #expect(throws: L10nError.self) {
            _ = try emit(["pt-br": #"{"a":"A"}"#, "pt-BR": #"{"a":"B"}"#])
        }
    }

    /// `SwiftWUIToolchain` cannot import `SwiftWUI`, so the tag grammar is
    /// duplicated. The test target sees both modules and pins them together —
    /// the emitter writes `LocaleID("<tag>")!`, so any drift is a boot-time trap.
    @Test func canonicalTagAgreesWithLocaleID() {
        for tag in ["en", "ru", "pt-br", "EN", "en_US", "zh-hans-cn", "es-419", "eng"] {
            #expect(LocaleID(tag) != nil, "LocaleID rejected \(tag)")
            #expect((try? L10nEmitter.canonicalTag(tag)) == LocaleID(tag)?.identifier, "tag \(tag)")
        }
        for tag in ["foo-bar", "e", "", "x = 1; import Foundation //", "en--US", "en-USA"] {
            #expect(LocaleID(tag) == nil, "LocaleID accepted \(tag)")
            #expect(throws: L10nError.self, "tag \(tag)") { try L10nEmitter.canonicalTag(tag) }
        }
    }

    /// A placeholder may be named after a locale; the per-locale local function
    /// must not shadow it.
    @Test func localFunctionsCannotShadowParameters() throws {
        let out = try emit(["en": #"{"k":"Hi, {en}!"}"#])
        #expect(out.contains("public static func k(en: String)"))
        #expect(out.contains("func _l_en() -> String"))
        #expect(out.contains(#"return "Hi, " + en + "!""#))
    }

    @Test func rejectsSymbolCollisions() {
        #expect(throws: L10nError.self) {
            var parsed: [String: [String: L10nTemplate]] = [:]
            parsed["en"] = try L10nCatalog.parse(json: #"{"a.b":"1","a-b":"2"}"#, locale: "en")
            _ = try L10nEmitter.file(catalogs: parsed)
        }
    }

    @Test func handlesWhatTheParserDefers() throws {
        // The parser (Task 3) validates keys and placeholder names as ASCII shapes
        // only; these cases reach the emitter and must not produce broken Swift.
        let keywords = try emit(["en": #"{"k":"{class} {func}"}"#])
        #expect(keywords.contains("public static func k(`class`: String, `func`: String)"))
        #expect(keywords.contains("`class` + \" \" + `func`"))

        #expect(throws: L10nError.self) { _ = try emit(["en": #"{"123":"x"}"#]) }
        #expect(throws: L10nError.self) { _ = try emit(["en": #"{"-":"x"}"#]) }
    }

    @Test func rejectsPluralInALanguageWithoutRules() {
        // Emitting `_SWUIPlural.vi(...)` for a language the generator has no CLDR
        // rule for would produce Swift that does not compile.
        #expect(throws: L10nError.self) {
            _ = try emit(["vi": #"{"n":"{count, plural, other {# mục}}"}"#])
        }
    }

    /// A key missing from a locale is absent from that locale's switch, so the
    /// runtime falls back; the exact tag is matched before the language.
    @Test func missingKeyFallsThroughAndExactTagWins() throws {
        let out = try emit(["en": #"{"a":"A","b":"B"}"#, "en-GB": #"{"a":"A!"}"#])
        let bBody = String(out[out.range(of: "public static func b(")!.lowerBound...])
        #expect(bBody.contains(#"case "en": return _l_en()"#))
        #expect(!bBody.contains("_l_enGB"))
        #expect(out.range(of: #"case "en-GB""#)!.lowerBound
                < out.range(of: "switch locale.language")!.lowerBound)
    }

    @Test func outputIsDeterministic() throws {
        let a = try emit(["ru": #"{"b":"Б","a":"А"}"#, "en": #"{"a":"A","b":"B"}"#])
        let b = try emit(["en": #"{"b":"B","a":"A"}"#, "ru": #"{"a":"А","b":"Б"}"#])
        #expect(a == b)
        // Equal key sets iterate identically within one process, so the equality
        // above cannot see unsorted iteration — pin the order itself.
        #expect(a.range(of: "static let en")!.lowerBound < a.range(of: "static let ru")!.lowerBound)
        #expect(a.range(of: "func a(")!.lowerBound < a.range(of: "func b(")!.lowerBound)
    }

    @Test func pluralRulesCoverRussian() {
        #expect(PluralRules.supported.contains("ru"))
        #expect(PluralRules.swiftBody(language: "xx") == nil)
        // A language in `supported` with no body would emit a call to a
        // `_SWUIPlural` member that is never defined.
        #expect(PluralRules.supported.allSatisfy { PluralRules.swiftBody(language: $0) != nil })
    }

    /// `abs(Int.min)` traps, and these bodies run inside the user's app.
    /// `value.magnitude` is total and agrees with `abs` everywhere else.
    @Test func pluralRulesNeverTrapOnIntMin() {
        for language in PluralRules.supported {
            #expect(!PluralRules.swiftBody(language: language)!.contains("abs("),
                    "\(language) uses abs()")
        }
    }

    /// `is` (Icelandic) and `as` (Assamese) are real subtags and Swift keywords;
    /// today neither is in `supported`, so only the escaper itself can be tested.
    @Test func pluralFunctionNamesEscapeKeywords() {
        #expect(L10nEmitter.escaped("is") == "`is`")
        #expect(L10nEmitter.escaped("as") == "`as`")
        #expect(L10nEmitter.escaped("ru") == "ru")
    }
}
