import Foundation

/// Turns parsed catalogs into `Generated/L10n.swift`.
///
/// Output shape (spec §2.2): one function per key returning `LocalizedText`,
/// per-locale bodies as local functions so each template is emitted once, an
/// exact-tag switch followed by a language switch, and `nil` for locales that
/// do not have the key (the runtime then falls back to the app default).
///
/// Every piece of catalog text reaches the output through
/// `SwiftLiteralEscaping.literal` — there is deliberately no second route.
public enum L10nEmitter {
    private static let swiftKeywords: Set<String> = [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
        "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
        "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "case", "continue",
        "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat",
        "return", "switch", "where", "while", "as", "catch", "false", "is", "nil", "super", "self",
        "Self", "throw", "throws", "true", "try", "any", "some",
    ]

    public static func symbolName(forKey key: String) throws -> String {
        let segments = key.split(whereSeparator: { $0 == "." || $0 == "-" || $0 == "_" }).map(String.init)
        guard let first = segments.first else { throw L10nError.unusableKey(key: key, symbol: "") }
        let head = first.prefix(1).lowercased() + first.dropFirst()
        let tail = segments.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
        let name = head + tail
        // The parser allows keys like "123" or "-": legal catalog keys, illegal Swift
        // identifiers. Refuse them here rather than emitting source that will not compile.
        guard let lead = name.first, lead.isASCII, lead.isLetter || lead == "_" else {
            throw L10nError.unusableKey(key: key, symbol: name)
        }
        return swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    /// Placeholder names become parameter names. The parser guarantees an ASCII
    /// identifier shape but not Swift legality: keywords need backticks, and `_`
    /// would generate a parameter the function body cannot reference.
    public static func parameterName(_ raw: String, key: String) throws -> String {
        guard raw != "_" else { throw L10nError.unusablePlaceholder(name: raw, key: key) }
        return swiftKeywords.contains(raw) ? "`\(raw)`" : raw
    }

    public static func symbolName(forTag tag: String) -> String {
        let segments = tag.split(separator: "-").map(String.init)
        guard let first = segments.first else { return "_" }
        let name = first + segments.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
        return swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    public static func file(catalogs: [String: [String: L10nTemplate]]) throws -> String {
        let locales = catalogs.keys.sorted()
        let allKeys = Set(catalogs.values.flatMap(\.keys)).sorted()

        var claimed: [String: String] = [:]                       // symbol -> key
        for key in allKeys {
            let symbol = try symbolName(forKey: key)
            if let existing = claimed[symbol] {
                throw L10nError.nameCollision(first: existing, second: key, symbol: symbol)
            }
            claimed[symbol] = key
        }

        // The file lands in the app's own target, so it carries its own import:
        // `LocaleID`, `LocalizedText`, `LocalizationCatalog` and `_PluralCategory`
        // all live in SwiftWUI.
        var out = """
        // Generated by `swiftwui l10n generate`. Do not edit.
        // Source of truth: Locales/*.json

        import SwiftWUI

        extension LocaleID {

        """
        for tag in locales {
            out += "    public static let \(symbolName(forTag: tag)) = LocaleID(\(SwiftLiteralEscaping.literal(tag)))!\n"
        }
        out += "}\n\npublic enum L10n {\n"
        for key in allKeys {
            out += try function(key: key, catalogs: catalogs, locales: locales)
        }
        out += "}\n\nextension L10n: LocalizationCatalog {\n"
        out += "    public static let supportedLocales: [LocaleID] = ["
        out += locales.map { "." + symbolName(forTag: $0) }.joined(separator: ", ")
        out += "]\n}\n"

        let pluralLanguages = try usedPluralLanguages(catalogs: catalogs, locales: locales)
        if !pluralLanguages.isEmpty {
            out += "\nenum _SWUIPlural {\n"
            for language in pluralLanguages.sorted() {
                guard let body = PluralRules.swiftBody(language: language) else { continue }
                // `nonisolated`: app targets build with `.defaultIsolation(MainActor.self)`,
                // and these run inside `LocalizedText`'s nonisolated render closure.
                out += "    nonisolated static func \(language)(_ value: Int) -> _PluralCategory {\n\(body)\n    }\n"
            }
            out += "}\n"
        }
        return out
    }

    private static func usedPluralLanguages(catalogs: [String: [String: L10nTemplate]],
                                            locales: [String]) throws -> Set<String> {
        var out: Set<String> = []
        for locale in locales {
            let language = String(locale.split(separator: "-")[0])
            let hasPlural = (catalogs[locale] ?? [:]).values.contains { template in
                template.parts.contains { if case .plural = $0 { return true } else { return false } }
            }
            guard hasPlural else { continue }
            // Without a rule the function body would call `_SWUIPlural.<lang>`, which
            // this file never defines. Fail here rather than emit uncompilable Swift.
            guard PluralRules.supported.contains(language) else {
                throw L10nError.unsupportedPluralLanguage(language: language, locale: locale)
            }
            out.insert(language)
        }
        return out
    }

    private static func function(key: String, catalogs: [String: [String: L10nTemplate]],
                                 locales: [String]) throws -> String {
        let present = locales.filter { catalogs[$0]?[key] != nil }
        let signature = L10nCatalog.signature(catalogs[present[0]]![key]!)
        var params = try signature.strings.map { "\(try parameterName($0, key: key)): String" }
        if let plural = signature.pluralVariable {
            params.append("\(try parameterName(plural, key: key)): Int")
        }
        let paramList = params.joined(separator: ", ")

        var out = "    public static func \(try symbolName(forKey: key))(\(paramList)) -> LocalizedText {\n"
        out += "        LocalizedText(key: \(SwiftLiteralEscaping.literal(key))) { locale in\n"
        for locale in present {
            let language = String(locale.split(separator: "-")[0])
            out += "            func \(symbolName(forTag: locale))() -> String {\n"
            out += try expression(catalogs[locale]![key]!, language: language, key: key,
                                  indent: "                ")
            out += "            }\n"
        }
        out += "            switch locale.identifier {\n"
        for locale in present {
            out += "            case \(SwiftLiteralEscaping.literal(locale)): return \(symbolName(forTag: locale))()\n"
        }
        out += "            default: break\n            }\n"
        out += "            switch locale.language {\n"
        for locale in present where !locale.contains("-") {
            out += "            case \(SwiftLiteralEscaping.literal(locale)): return \(symbolName(forTag: locale))()\n"
        }
        out += "            default: return nil\n            }\n"
        out += "        }\n    }\n"
        return out
    }

    private static func expression(_ template: L10nTemplate, language: String, key: String,
                                   indent: String) throws -> String {
        // A plural key becomes a switch; a plain key becomes one return.
        if let index = template.parts.firstIndex(where: { if case .plural = $0 { return true } else { return false } }),
           case .plural(let variable, let branches) = template.parts[index] {
            let prefix = Array(template.parts[..<index])
            let suffix = Array(template.parts[(index + 1)...])
            let parameter = try parameterName(variable, key: key)
            var out = "\(indent)switch _SWUIPlural.\(language)(\(parameter)) {\n"
            for branch in branches where branch.category != "other" {
                out += "\(indent)case .\(branch.category): return "
                out += try concat(prefix + branch.parts + suffix, pluralVariable: variable, key: key) + "\n"
            }
            let other = branches.first { $0.category == "other" }!
            out += "\(indent)default: return "
            out += try concat(prefix + other.parts + suffix, pluralVariable: variable, key: key) + "\n"
            out += "\(indent)}\n"
            return out
        }
        return "\(indent)return " + (try concat(template.parts, pluralVariable: nil, key: key)) + "\n"
    }

    private static func concat(_ parts: [L10nPart], pluralVariable: String?, key: String) throws -> String {
        var pieces: [String] = []
        for part in parts {
            switch part {
            case .literal(let s): pieces.append(SwiftLiteralEscaping.literal(s))
            case .placeholder(let n): pieces.append(try parameterName(n, key: key))
            case .number:
                pieces.append("String(\(try parameterName(pluralVariable ?? "count", key: key)))")
            case .plural: continue                              // flattened by the caller
            }
        }
        return pieces.isEmpty ? "\"\"" : pieces.joined(separator: " + ")
    }
}
